### ISSUE TITLE
cuda内存不够报错

### ISSUE THREAD

**Issue by happy724** [204313508/noname_llm#2]
![屏幕截图 2023-12-02 120854](https://github.com/204313508/noname_llm/assets/122508527/97f1f8b0-9cdf-4c7c-af2f-269992bc4d16)
这是我的nvcc -V运行结果可以看出是没有问题的
打开demo.exe 
运行结果保持一段时间
![ee039c978c661cdbaefdf4bbb0fcca4](https://github.com/204313508/noname_llm/assets/122508527/f42a5f8c-e0a5-42be-83a4-dea59a10b49f)
之后快速闪过
![50efb3f259872fb4f96ca78a5a89623](https://github.com/204313508/noname_llm/assets/122508527/143f84aa-afeb-45bd-92f2-1b5d01e1930c)
之后终端关闭，似乎是内存不够的问题，但我是4G显存16G内存10G虚拟内存也不满足要求吗
同时在运行过程中GPU始终没有占用
![image](https://github.com/204313508/noname_llm/assets/122508527/813e1ed2-890c-44c2-b83f-7135f4a6bdc4)

**Comment by 204313508** [comment]
暂时无法使用，条件里有说明显存的全部+物理内存的一半要达到16G，4G显存16G内存的话加起来只有12G，如果有需求可以等待后续量化或cpu版本，但量化版本效果会差一些

**Comment by happy724** [comment]
![image](https://github.com/204313508/noname_llm/assets/122508527/74f64a8d-e072-495d-b37d-605b0295d1cf)
这是我的虚拟内存配置

**Comment by 204313508** [comment]
因为共享显存设置，只有物理内存是可以充当显存的，虚拟内存对于显存容量是没有帮助的

**Comment by happy724** [comment]
> 因为共享显存设置，只有物理内存是可以充当显存的，虚拟内存对于显存容量是没有帮助的

也就是说，这个项目实际是需要共享gpu+独享gpu大于16G对吧

**Comment by 204313508** [comment]
对的，目前发布的懒人包是使用cuda推理的，cuda推理需要共享gpu+独享gpu达到16G，如果不满足这个条件的话可以搭建环境并使用cpu推理，或者等待cpu版懒人包，那个理论只需要内存（可以包括虚拟内存）达到32G即可，但是速度会慢一些，并且效果可能会差一些
